version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: yt-dlp:master    # Required. Must be in the same fork network.
    mergeMethod: merge  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
